services:
  db:
    image: mariadb:lts
    container_name: piikki_db
    restart: unless-stopped

    secrets:
      - db_root_password

    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: piikki

    volumes:
      - db_data:/var/lib/mysql

    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  migration:
    build:
      context: .
      dockerfile: ./db/migration.Dockerfile
    container_name: piikki_db_migration
    restart: 'no'

    depends_on:
      db:
        condition: service_healthy

    secrets:
      - db_root_password 
      - db_app_user
      - db_app_password

    entrypoint: >
      sh -c "
        export ROOT_PASSWORD=$$(cat /run/secrets/db_root_password);
        export APP_USER=$$(cat /run/secrets/db_app_user);
        export APP_PASSWORD=$$(cat /run/secrets/db_app_password);

        mysql -h db -u root -p\"$$ROOT_PASSWORD\" piikki < /db/create_schema.sql;
        mysql -h db -u root -p\"$$ROOT_PASSWORD\" piikki < /db/create_test_data.sql;
        mysql -h db -u root -p\"$$ROOT_PASSWORD\" piikki < /db/create_search_index.sql;

        cat /db/create_users.sql | \
        sed -e \"s/APP_USER_PLACEHOLDER/$$APP_USER/g; s/APP_PASSWORD_PLACEHOLDER/$$APP_PASSWORD/g\" | \
        mysql -h db -u root -p\"$$ROOT_PASSWORD\" piikki;
      "

    volumes:
      - ./db:/db

  web_builder:
    build:
      context: ./web
      dockerfile: build.Dockerfile

    volumes:
      - web_assets:/app/build

    develop:
      watch:
        - path: ./web
          action: rebuild

  web_app:
    build:
      context: .
      dockerfile: ./cmd/dev_web_app/Dockerfile

    develop:
      watch:
        - path: ./cmd/dev_web_app
          action: rebuild
        - path: ./pkg
          action: rebuild

    container_name: piikki_dev_web
    restart: unless-stopped

    depends_on:
      migration:
        condition: service_completed_successfully 

    environment:
      HOST_URL: "https://karsimys.stadi.ninja"

    secrets:
      - db_app_user
      - db_app_password

    entrypoint: >
      sh -c "
        export APP_USER=$$(cat /run/secrets/db_app_user);
        export APP_PASSWORD=$$(cat /run/secrets/db_app_password);

        export DATABASE_APP=\"$$APP_USER:$$APP_PASSWORD@tcp(db:3306)/piikki\";
        
        exec web-app
      "

  nginx:
    image: nginx:latest
    container_name: nginx_dev
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx_dev.conf:/etc/nginx/conf.d/default.conf:ro
      - web_assets:/var/www/static:ro
    depends_on:
      web_app:
        condition: service_started

volumes:
  db_data:
    driver: local

  web_assets:

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt

  db_app_user:
    file: ./secrets/db_app_user.txt
  db_app_password:
    file: ./secrets/db_app_password.txt

