services:
  watchtower:  # Watches for updates to web app or telegram bot images
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600  # Interval (seconds) for polling Docker Hub
    restart: unless-stopped  # Auto-restart if the container crashes

  webapp:
    image: lattots/piikki-web:latest  # What image to use
    network_mode: "host"  # Use host networking
    container_name: web-app-container  # Set the container name
    restart: unless-stopped  # Auto-restart if the container crashes

  telegram-bot:
    image: lattots/piikki-bot:latest  # What image to use
    network_mode: "host"  # Use host networking
    container_name: telegram-bot-container  # Set the container name
    restart: unless-stopped  # Auto-restart if the container crashes
