openapi: 3.1.1
info:
  title: Piikki Web API
  version: 0.0.1
paths:
  /users:
    get:
      summary: Fetch users
      parameters:
        - name: searchTerm
          in: query
          schema:
            type: string
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"

  /users/{userId}:
    get:
      summary: Fetch a single user by ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: User found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: User not found

  /users/{userId}/transactions:
    get:
      summary: Get user transactions
      parameter:
        - name: quantity
          in: query
          schema:
            type: quantity
      response:
        "200":
          description: Transactions found
          content:
            application/json:
              schema:
                type: array
                $ref: "#/components/schemas/Transactions"

    post:
      summary: Create a transaction
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer     
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Transaction"
      responses:
        "201":
          description: Transaction successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "402":
          description: Insufficient funds

  /transactions:
    get:
      summary: Get transactions in a time window (for example transactions from 30 days before Dec 1st)
      parameters:
        - name: window
          description: Length of the time window in hours (max 10 * 365 * 24)
          in: query
          required: true
          schema:
            type: integer
        - name: endDate
          description: End of the transaction window in RFC3339 (defaults to the current date if not provided)
          in: query
          required: false
          schema:
            type: date-time
        - name: type
          description: Only include certain transaction types (deposit / withdraw / all)
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: List of transactions
          content:
            application/json:
              schema:
                type: array
                $ref: "#/components/schemas/Transaction"
        "400":
          description: Error parsing parameters
        "416":
          description: Transaction window is invalid. End date is in the future or window length is negative

components:
  schemas:
    User:
      type: object
      properties:
        id: { type: integer }
        username: { type: string }
        firstName: { type: string }
        lastName: { type: string }
        balance: { type: integer, description: "Balance in cents" }
    Transaction:
      type: object
      required: [type, amount]
      properties:
        issuer: { type: string }
        issuedAt: { type: date-time, description: "Time stamp of transaction as RFC3339"}
        type: { type: string, enum: [withdraw, deposit] }
        amount: { type: integer, description: "Amount in cents" }
