CREATE USER 'APP_USER_PLACEHOLDER'@'%' IDENTIFIED BY 'APP_PASSWORD_PLACEHOLDER';

GRANT SELECT, INSERT, UPDATE, DELETE ON piikki.users TO 'APP_USER_PLACEHOLDER'@'%';
GRANT SELECT, INSERT ON piikki.transactions TO 'APP_USER_PLACEHOLDER'@'%';

FLUSH PRIVILEGES;
