name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Make script executable
        run: chmod +x ./cicd/create_env_file.sh

      - name: Create .env File
        run: ./cicd/create_env_file.sh
        env:
          DATABASE_ADMIN: ${{ secrets.DATABASE_ADMIN }}
          DATABASE_APP: ${{ secrets.DATABASE_APP }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          COOKIE_STORE_SECRET: ${{ secrets.COOKIE_STORE_SECRET }}
          HOST_URL: ${{ secrets.HOST_URL }}
          PORT: ${{ secrets.PORT }}

      - name: Copy .env To Server
        uses: appleboy/scp-action@master
        env:
          USERNAME: ${{ secrets.USERNAME }}
          HOST: ${{ secrets.HOST }}
          KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source: './deploy/.env'
          target: '/home/${{ secrets.USERNAME }}/piikittaja/deploy/.env'

      - name: Build Telegram Bot
        run: make build-bot

      - name: Deploy Telegram Bot
        run: make deploy-bot

      - name: Build Web App
        run: make build-web

      - name: Deploy Web App
        run: make deploy-web

      - name: Build Reminder
        run: make build-reminder

      - name: Deploy Reminder
        run: make deploy-reminder

      - name: Build Admin Manager
        run: make build-manager

      - name: Deploy Admin Manager
        run: make deploy-manager

      - name: Build Messenger
        run: make build-messenger

      - name: Deploy Messenger
        run: make deploy-messenger
